# Generated by Django 3.0.7 on 2020-10-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
