# Generated by Django 3.0.7 on 2020-10-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='squirrel_id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=256, primary_key=True, serialize=False),
        ),
    ]
