# Generated by Django 3.0.7 on 2020-10-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20201019_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='squirrel_id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=256, primary_key=True, serialize=False, unique=True),
        ),
    ]
