# Generated by Django 3.0.7 on 2020-10-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20201019_1801'),
        ('sightings', '0004_auto_20201019_1627'),
    ]

    operations = [
    ]
