# Generated by Django 3.0.7 on 2020-10-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20201019_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='longitude',
            new_name='longtitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='tail_flag',
            new_name='tail_flags',
        ),
    ]
