# Generated by Django 3.0.7 on 2020-10-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20201020_0408'),
        ('sightings', '0007_auto_20201020_0240'),
    ]

    operations = [
    ]
