# Generated by Django 3.0.7 on 2020-10-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0009_auto_20201020_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
